name: odc-shim
defaults:
  odc_hostname: localhost
  odc_port: "50051"
  user: flp
control:
  mode: direct
wants:
  cpu: 0.01
  memory: 3
properties:
  environment_id: "{{ environment_id }}" # we must pass this as property because o2-aliecs-odc-shim expects it
command: 
  env: []
  shell: true
  user: "{{ user }}"
  arguments: []
  value: >-
    eval `aliswmod load Control-OCCPlugin` &&
    o2-aliecs-odc-shim {{odc_hostname}}:{{odc_port}}
